import { UserData, UserRank } from "./index.d";

export const users: UserData[] = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    country: "USA",
    city: "New York",
    address: "123 Main St",
    referredBy: null,
    phoneNumber: "1234567890",
    referralCode: "ABC123",
    email: "john.doe@example.com",
    balance: 100,
    claimable: 10,
    oneDollar: 5,
    earningsHistory: [],
    investments: [],
    createdAt: new Date(),
    promotion: 0,
    status: "active",
    role: "user",
    hasActiveInvestment: false,
    accountActivated: true,
    updatedAt: new Date(),
    isVerified: true,
    rank: UserRank.USER,
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    country: "Canada",
    city: "Toronto",
    address: "456 Elm St",
    referredBy: null,
    phoneNumber: "9876543210",
    referralCode: "DEF456",
    email: "jane.smith@example.com",
    balance: 200,
    claimable: 20,
    oneDollar: 10,
    earningsHistory: [],
    investments: [],
    createdAt: new Date(),
    promotion: 5,
    status: "active",
    role: "user",
    hasActiveInvestment: true,
    accountActivated: true,
    updatedAt: new Date(),
    isVerified: true,
    rank: UserRank.ASSOCIATE_GROUP_LEADER,
  },
  {
    id: 3,
    firstName: "Alice",
    lastName: "Johnson",
    country: "UK",
    city: "London",
    address: "789 Oak St",
    referredBy: null,
    phoneNumber: "1231231234",
    referralCode: "GHI789",
    email: "alice.johnson@example.com",
    balance: 150,
    claimable: 15,
    oneDollar: 7,
    earningsHistory: [],
    investments: [],
    createdAt: new Date(),
    promotion: 10,
    status: "active",
    role: "user",
    hasActiveInvestment: false,
    accountActivated: true,
    updatedAt: new Date(),
    isVerified: false,
    rank: UserRank.GROUP_LEADER,
  },
  {
    id: 4,
    firstName: "Bob",
    lastName: "Brown",
    country: "Australia",
    city: "Sydney",
    address: "101 Pine St",
    referredBy: null,
    phoneNumber: "9879879876",
    referralCode: "JKL012",
    email: "bob.brown@example.com",
    balance: 50,
    claimable: 5,
    oneDollar: 2,
    earningsHistory: [],
    investments: [],
    createdAt: new Date(),
    promotion: 0,
    status: "blocked",
    role: "admin",
    hasActiveInvestment: false,
    accountActivated: false,
    updatedAt: new Date(),
    isVerified: true,
    rank: UserRank.MASTER_LEADER,
  },
  {
    id: 5,
    firstName: "Charlie",
    lastName: "Davis",
    country: "India",
    city: "Mumbai",
    address: "202 Palm St",
    referredBy: null,
    phoneNumber: "4564564567",
    referralCode: "MNO345",
    email: "charlie.davis@example.com",
    balance: 75,
    claimable: 8,
    oneDollar: 3,
    earningsHistory: [],
    investments: [],
    createdAt: new Date(),
    promotion: 2,
    status: "active",
    role: "moderator",
    hasActiveInvestment: true,
    accountActivated: true,
    updatedAt: new Date(),
    isVerified: false,
    rank: UserRank.ASSOCIATE_MASTER_LEADER,
  },
  {
    id: 6,
    firstName: "Ella",
    lastName: "Evans",
    country: "Germany",
    city: "Berlin",
    address: "303 Maple St",
    referredBy: null,
    phoneNumber: "7897897891",
    referralCode: "PQR678",
    email: "ella.evans@example.com",
    balance: 120,
    claimable: 12,
    oneDollar: 6,
    earningsHistory: [],
    investments: [],
    createdAt: new Date(),
    promotion: 3,
    status: "active",
    role: "user",
    hasActiveInvestment: true,
    accountActivated: true,
    updatedAt: new Date(),
    isVerified: true,
    rank: UserRank.LEADING_LEADER,
  },
  {
    id: 7,
    firstName: "George",
    lastName: "Foster",
    country: "France",
    city: "Paris",
    address: "404 Birch St",
    referredBy: null,
    phoneNumber: "3213213210",
    referralCode: "STU901",
    email: "george.foster@example.com",
    balance: 90,
    claimable: 9,
    oneDollar: 4,
    earningsHistory: [],
    investments: [],
    createdAt: new Date(),
    promotion: 4,
    status: "active",
    role: "user",
    hasActiveInvestment: false,
    accountActivated: true,
    updatedAt: new Date(),
    isVerified: true,
    rank: UserRank.CROWN_LEADER,
  },
  {
    id: 8,
    firstName: "Hannah",
    lastName: "Green",
    country: "Japan",
    city: "Tokyo",
    address: "505 Cedar St",
    referredBy: null,
    phoneNumber: "6546546543",
    referralCode: "VWX234",
    email: "hannah.green@example.com",
    balance: 110,
    claimable: 11,
    oneDollar: 5,
    earningsHistory: [],
    investments: [],
    createdAt: new Date(),
    promotion: 5,
    status: "active",
    role: "user",
    hasActiveInvestment: true,
    accountActivated: true,
    updatedAt: new Date(),
    isVerified: true,
    rank: UserRank.PRINCE_OF_OMNI_STOCK,
  },
  {
    id: 9,
    firstName: "Ian",
    lastName: "Hughes",
    country: "Brazil",
    city: "Rio de Janeiro",
    address: "606 Spruce St",
    referredBy: null,
    phoneNumber: "1112223334",
    referralCode: "XYZ567",
    email: "ian.hughes@example.com",
    balance: 95,
    claimable: 9.5,
    oneDollar: 4.5,
    earningsHistory: [],
    investments: [],
    createdAt: new Date(),
    promotion: 3,
    status: "active",
    role: "user",
    hasActiveInvestment: false,
    accountActivated: true,
    updatedAt: new Date(),
    isVerified: false,
    rank: UserRank.ASSOCIATE_LEADING_LEADER,
  },
  {
    id: 10,
    firstName: "Julia",
    lastName: "Adams",
    country: "South Africa",
    city: "Cape Town",
    address: "707 Walnut St",
    referredBy: null,
    phoneNumber: "5556667778",
    referralCode: "QRS890",
    email: "julia.adams@example.com",
    balance: 130,
    claimable: 13,
    oneDollar: 6.5,
    earningsHistory: [],
    investments: [],
    createdAt: new Date(),
    promotion: 6,
    status: "active",
    role: "user",
    hasActiveInvestment: true,
    accountActivated: true,
    updatedAt: new Date(),
    isVerified: true,
    rank: UserRank.LEADING_LEADER,
  },
];
